#mybatis:
#  type-aliases-package: com.yaya.domain
#  mapper-locations: classpath*:com/yaya/mapper/*Mapper.xml

mybatis-plus:
  type-aliases-package: com.yaya.domain
  mapper-locations: classpath*:com/yaya/mapper/*Mapper.xml
  type-enums-package: com.yaya.enums
  global-config:
    db-config:
      id-type: auto
#  数据结果在控制台显示
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  # 设置logback.xml位置
  #  config: classpath:log/logback.xml
  # 设置log4j.properties位置
#  config: classpath:log4j.properties
#  level:
#    com.yaya: warn



#  typeAliases


spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
  datasource:
    druid:
#   url: jdbc:h2:~/test
#    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://119.29.197.52:3306/mp?useSSL=false
      username: YaYa
      password: YaYaisGood.
#      driver-class-name: org.h2.Driver
#      name: sa
#      password: 123456
server:
  port: 8080
